name: Gerar animação da cobrinha

on:
  schedule:
    - cron: "0 0 * * *" # O job vai rodar a cada 24 horas

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: EnzoBelfort
          gif_out_path: ./dist/github-snake.gif
          svg_out_path: ./dist/github-snake.svg

      - uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Gera animação da cobrinha'
          add: 'dist/github-snake.svg dist/github-snake-dark.svg'
